name: Deploy Release (tag) to Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The target environment"
        required: true
        type: choice
        options:
          - dev

concurrency:
  group: "release"
  cancel-in-progress: false

jobs:
  abort-branch-execution:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Prevent manual deployments from a branch
        if: github.ref_type == 'branch'
        run: |-
          echo "Deploying a branch is not supported. Select a tag instead of a branch when clicking 'Use workflow' instead. env: ${{secrets.ENVIRONMENT}}"
          exit 1
  deploy-to-environment:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    needs: abort-branch-execution

    steps:
      - name: Hello
        run: |-
          echo "HELLO"
          exit 1
